CREATE TABLE block_request (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    card_id BIGINT NOT NULL,
    reason VARCHAR(4096) NOT NULL,
    executed BOOLEAN NOT NULL DEFAULT false
);